name = "grammarly-ai-humanizer"
compatibility_date = "2026-07-03"
compatibility_flags = [ "nodejs_compat", "nodejs_compat_populate_process_env" ]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

[[kv_namespaces]]
binding = "SESSION"
id = "25f056c216c04f89aed49f1f04f2651f"

